import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; 
import BottomNav from "@/components/BottomNav";
import FloatingWidget from '@/components/FloatingWidget';
import ConditionalMarquee from "@/components/ConditionalMarquee";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-black`} 
    >
      <body className="min-h-full flex flex-col items-center"> 
        <div className="w-full max-w-[1200px] bg-transparent shadow-2xl">
          <Header />
          <BottomNav />
          <FloatingWidget />
          {/* Gunakan komponen yang sudah memiliki logika deteksi URL */}
          <ConditionalMarquee />

          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}